# Generated by Django 5.0 on 2024-01-10 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0002_product_pimage_alter_product_cat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pimage',
        ),
    ]
